# Generated by Django 5.2.3 on 2025-07-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_alter_userbadge_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='badge.userbadge')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('condition_description', models.CharField(max_length=255)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='badge.badge')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('badge', 'level')},
            },
        ),
    ]
