# Generated by Django 5.2.3 on 2025-07-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_badgelog_badgelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
