# Generated by Django 5.2.3 on 2025-07-03 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0004_badge_level'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='level',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='previous_badge',
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge', to='category.category'),
        ),
        migrations.DeleteModel(
            name='BadgeLevel',
        ),
    ]
