# Generated by Django 5.2.3 on 2025-07-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_answer_likes_answerreport'),
        ('main', '0004_remove_user_last_login_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_answers', to='main.user'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.user'),
        ),
        migrations.AlterField(
            model_name='answerreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_reports', to='main.user'),
        ),
    ]
