# Generated by Django 5.2.4 on 2025-07-05 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("question", "0006_alter_bookmark_user_alter_question_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="anony",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="category.category",
            ),
            preserve_default=False,
        ),
    ]
