# Generated by Django 5.2.4 on 2025-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("question", "0007_question_anony_alter_question_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.AddField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(
                related_name="questions", to="category.category"
            ),
        ),
    ]
